### ISSUE TITLE
can you guess what this is?

### ISSUE THREAD

**Issue by alucantonio** [mathLab/pi-DoMUS#104]
![logo_pidomus](https://cloud.githubusercontent.com/assets/14178111/11842752/ee40d966-a405-11e5-953d-3520b7cd279d.png)

**Comment by ESeNonFossiIo** [comment]
Come si fa a bannare qualcuno in github? :D

**Comment by alucantonio** [comment]
;-)

**Comment by asartori86** [comment]
la casa del sig. Pi Greco

**Comment by luca-heltai** [comment]
:+1:
