### ISSUE TITLE
Solve/System/Preconditioner

### ISSUE THREAD

**Issue by luca-heltai** [mathLab/pi-DoMUS#151]
Right now, we have something like 

```
compute_system_operators(...);
```

Should we split this into separate functions, only called if necessary?

**Comment by asartori86** [comment]
I would lean to 

```
compute_system_operator(*matrices, system_op, prec_op)
```

which is the present implementation (this is called only when we use iterative solver, so I guess we always need to define a preconditioner). Plus

```
compute_fine_preconditioner(*matrices, finer_op)
```

this should be called within the catch block if the proper flag (if any) is set

**Comment by ESeNonFossiIo** [comment]
Imagine the case you have a block preconditioner and fine and coarse preconditioners differ from just one block. In this case you have to rewrite a lot of code...

I am thinking to the case of a stokes preconditioner and 

```
  A_inv  = linera_operator(block(0,0), AMG)
  prec = combination of Mp, A_inv, B 
```

as coarse preconditioner and 

```
  A_inv_fine  = inverse_operator(block(0,0), AMG)
  prec = combination of Mp, A_inv_fine, B 
```

as fine preconditioner.
The major part of applications I have in mind have this structure...

**Comment by ESeNonFossiIo** [comment]
Look at _include/interfaces/navier_stokes.h_ of my PR.
This is the case.

**Comment by luca-heltai** [comment]
Ok, then finish writing the documentation of all functions involved in compute_system_operators, including examples, and we'll merge your PR.

**Comment by asartori86** [comment]
il numero di iterazioni nel primo tentativo?
