### ISSUE TITLE
Navier Stokes preconditioners

### ISSUE THREAD

**Issue by luca-heltai** [mathLab/pi-DoMUS#18]
- [x] Check that the current preconditioner for Stokes works with Linear Operators
- [x] Write a section in the Navier-Stokes interface, to select different preconditioners, and assemble the right one according to the parameter file (TODO: choose a list of preconditioners for the tests)
- [x] Make the grid and manifold descriptor for two  benchmarks of Navier-Stokes:
  - [x] Lid Cavity problem
  - [x] Flow past a cylinder
- [x] Test all implemented preconditioners on the two problems above, checking scalability, for different Reynolds Numbers: 1, 10, 100, 1.000, 10.000 (not all preconditioners will work everywhere)
- [x] Repeat the tests above with a different selection of Finite Element system (Q(3)-Q(2)/Q(4)-Q(3))

**Comment by luca-heltai** [comment]
@ESeNonFossiIo , punto uno e' fatto? (se si: spunta..)

**Comment by ESeNonFossiIo** [comment]
Se basta che l'implementazione usata in step-32 funziona ok: assemblo i blocchi come linear operator e assemblo il precondizionatore usando questi blocchi. Senza usare back o forward.

**Comment by ESeNonFossiIo** [comment]
![lidcavity](https://cloud.githubusercontent.com/assets/8956997/11016047/4800f2a6-8575-11e5-87fb-c86aa11a655b.png)

**Comment by ESeNonFossiIo** [comment]
$\nu=200$

**Comment by luca-heltai** [comment]
Figo!

**Comment by ESeNonFossiIo** [comment]
per $Flow past a cylinder$ avete una griglia già fatta da passarmi? ... o implementiamo il grid merge in grid generator?

**Comment by luca-heltai** [comment]
deve essere negli esempi di deal2lkit

**Comment by ESeNonFossiIo** [comment]
Da un test come si carica un file? non mi trova il path.

**Comment by ESeNonFossiIo** [comment]
![movie0089](https://cloud.githubusercontent.com/assets/8956997/11020876/b03b17de-862e-11e5-9c9a-6e71ec240436.jpeg)
con \nu = 10

**Comment by ESeNonFossiIo** [comment]
se metto \nu~0.1 non converge

**Comment by ESeNonFossiIo** [comment]
![movie0118](https://cloud.githubusercontent.com/assets/8956997/11338780/5ecb89e6-91f6-11e5-8728-d29dfae57e95.png)

**Comment by ESeNonFossiIo** [comment]
Re ~ 400

**Comment by ESeNonFossiIo** [comment]
v=2*t per t<.5
v=1 per t>=.5
immagine presa a tempo t~1.2

**Comment by ESeNonFossiIo** [comment]
![movie0219](https://cloud.githubusercontent.com/assets/8956997/11338855/cd9e5f06-91f6-11e5-89ee-50a3f0e25124.png)

**Comment by ESeNonFossiIo** [comment]
t~2.2

**Comment by ESeNonFossiIo** [comment]
![movie0321](https://cloud.githubusercontent.com/assets/8956997/11338869/ddc15a28-91f6-11e5-9bed-7d5f9f777b1e.png)

**Comment by ESeNonFossiIo** [comment]
t~3.2
