### ISSUE TITLE
Implement forcing term for non-conservative interface

### ISSUE THREAD

**Issue by ESeNonFossiIo** [mathLab/pi-DoMUS#24]
**virtual void get_preconditioner_residual** of _non_conservative_interfaces_ does not uses forcing term.

**Comment by asartori86** [comment]
in non conservative case the user must overwrite that function to fit the specific problem

**Comment by ESeNonFossiIo** [comment]
and the user is supposed to implement the forcing term?

**Comment by asartori86** [comment]
the forcing terms and neumann bcs can be set through parameter file. It is up to the user apply them in the residual i.e. call `apply_forcing_terms` and `apply_neumann_bcs`

**Comment by luca-heltai** [comment]
This should be **well** documented...

**Comment by ESeNonFossiIo** [comment]
To be honest, I did not understand it...

**Comment by asartori86** [comment]
anzi, `apply_forcing_terms` and `apply_neumann_bcs` vogliono una energia

**Comment by luca-heltai** [comment]
At the moment, the only working interface is the conservative one. The non conservative does not have forcing terms...

**Comment by luca-heltai** [comment]
`apply_forcing_terms` and `apply_neumann_bcs` should be specialized to act also on a residual vector

**Comment by asartori86** [comment]
Ok I'll take care of it
