### ISSUE TITLE
refine_mesh

### ISSUE THREAD

**Issue by ESeNonFossiIo** [mathLab/pi-DoMUS#25]
At the moment **refine_mesh** is useless. It is never called.
Should we move it in _solver_should_restart_? or there is a better implementation?

**Comment by asartori86** [comment]
si rimuovi pure. era una versione alpha di quello che si fa nel solver should restart

**Comment by ESeNonFossiIo** [comment]
Allora la PR #10 (Kelly estimator) di piDoMUS va implementata in D2K...

**Comment by luca-heltai** [comment]
mmmmm. Nope. pi-DoMUS is derived from sundials interface. It has to reimplement `solver_should_restart`. So `refine_mesh` should be removed, and `solver_should_restart` should become similar to `heat_ida`

**Comment by asartori86** [comment]
dobbiamo rimuovere la funzione refine mesh?
