### ISSUE TITLE
Additional preconditioners

### ISSUE THREAD

**Issue by ESeNonFossiIo** [mathLab/pi-DoMUS#61]
In some cases one preconditioner it is not enough. Think to the case when you have to assemble Ap, Fp, and Mp. Ap could be assembled in the preconditioner, Fp in the system matrix, and Mp ... ?

These objects should have the following characteristics:
- they could be assembled in the same way we assemble preconditioner or system matrix (energy/residual)
- we do not need a global LinearOperator for them. They are used just to assemble blocks.
- when we write an interface we know how much these matrices are.
- matrices could be pxp, pxv, or vxv.

A possible way to do that is the following:
1. add a **vector** of **vector of shared pointer** of **aux_matrix** in _pdomus.h \* 
2. implement a virtual method to fill them up in *interface.h_
3. this method should take into account boundary conditions and time dependency. (sundials derivative?)
4. In case these matrices are required reimplement the method in the problem interface. 

@asartori86 and @luca-heltai any ideas?

**Comment by ESeNonFossiIo** [comment]
ping

**Comment by luca-heltai** [comment]
a vector of shared pointers matrices seems reasonable to me.

**Comment by luca-heltai** [comment]
Proposal:

```
virtual constexpr const unsigned int Interface::n_preconditioner_matrices();
```

default return value: 1.

```
std::vector<shared_ptr<LAC::MatrixType> > preconditioner_matrices;
```

initialized with `this->n_preconditioner_matrices()`.

When assemble preconditioner is called, a loop over all preconditioner_matrices is done, and an additional index is passed to the function computing the residual, which tells the residual which matrix to assemble.

**Comment by asartori86** [comment]
> virtual constexpr const unsigned int Interface::n_preconditioner_matrices();

se lo passassimo da file di parametri?

**Comment by asartori86** [comment]
possiamo chiudere questo?
