### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by ESeNonFossiIo** [mathLab/pi-DoMUS#75]
[error.txt](https://files.zenhub.io/564da8082d47521d4101d6db)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by luca-heltai** [comment]
for every unused parameter in the function, add this at the end to remove the warnings.

```
(void) unused_par;
```

**Comment by asartori86** [comment]
I'll do that in my `revolution` :)
