### ISSUE TITLE
New interface is broken 

### ISSUE THREAD

**Issue by luca-heltai** [mathLab/pi-DoMUS#86]
The new interface requires the function `Interface::Init()` to be called, but pi-DoMUS does not call it anywhere... I think the content of the Init function should end up directly in the constructor.

Time dependency of the IMEXTimeStepper seems to be broken in pi-DoMUS

See branch:

https://github.com/luca-heltai/pi-DoMUS/tree/scalar-reaction-diffusion

If you put the time dependence in the equation (we tried this with @gpitton ), nans appear in the matrix, and everything fails...

It suffices to put in the residual `ut*v` instead of `u*v` to see this

**Comment by asartori86** [comment]
> The new interface requires the function Interface::Init() to be called, but pi-DoMUS does not call it anywhere... I think the content of the Init function should end up directly in the constructor.

which constructor? we may just call that function within the constructor of pi-DoMUS.

> Time dependency of the IMEXTimeStepper seems to be broken in pi-DoMUS

is this an issue of the IMEXTimeStepper itself (i.e., we need to address it in deal2lkit) or pi-DoMUS?

**Comment by luca-heltai** [comment]
Why do we need a separate `init()` function? I'm in favour of putting its content in the constructor of `BaseInterface`

**Comment by luca-heltai** [comment]
I don't know if the issue is with `IMEXTimeStepper`, or with `pi-DoMUS`...

**Comment by asartori86** [comment]
> Why do we need a separate init() function? I'm in favour of putting its content in the constructor of BaseInterface

It calls virtual functions so it cannot be inside the constructor of the base class

**Comment by asartori86** [comment]
> I don't know if the issue is with IMEXTimeStepper, or with pi-DoMUS...

what happens with ida?

**Comment by asartori86** [comment]
@luca-heltai @gpitton, I tried a simple poisson equation time-dep with both ida and euler and it seems to work.

**Comment by ESeNonFossiIo** [comment]
I have problems with both euler and ida. 
Old tests do not work with the new interface.
Sometimes it seems to work and it breaks after a refinement.

**Comment by asartori86** [comment]
> Sometimes it seems to work and it breaks after a refinement.

this is because of #72

**Comment by asartori86** [comment]
> I have problems with both euler and ida. 
> Old tests do not work with the new interface.

what kind of problems?

**Comment by ESeNonFossiIo** [comment]
I am not using adaptivity and old_solutions.

**Comment by ESeNonFossiIo** [comment]
1. No convergence in tests I wrote for the old interface.
2. Sometime it requires a lot of time (10 minutes) for one step of a system (187Dof)

**Comment by ESeNonFossiIo** [comment]
Now, my tests are ok. Some parameters needed to be tuned...

**Comment by ESeNonFossiIo** [comment]
I have pushed tests for stokes and dynamic stokes. These tests looks good and works.
I noticed some strange behaviour with direct method with non time depending problems: if you use the right solution as initial solution, the method will pass. Otherwise it does not.
Am I doing something wrong? Or did I not consider something?
Euler and Ida seem ok.
