### ISSUE TITLE
new name per `Interface`

### ISSUE THREAD

**Issue by asartori86** [mathLab/pi-DoMUS#90]
as proposed by @alucantonio 
- `PDEInteface`
- `PhysicsInterface`
- `PDEsInterface`
- `ProblemInterface`
- `piDoMUSProblem`

**Comment by asartori86** [comment]
@alucantonio ha proposto anche
- `PDESystem`
- `MutliPhysicsSystem`

**Comment by luca-heltai** [comment]
`PDEInterface` mi piace. Anche `PDESystemInterface`, così mettiamo insieme i due concetti... scegliete voi

**Comment by asartori86** [comment]
@ESeNonFossiIo ?

**Comment by ESeNonFossiIo** [comment]
Non ho preferenze. Il nome che scegliete è quello che mi piace di più. :)
